---
title: "ProyectoTD2024"
output: html_document
date: "2024-03-26"
authors: "Marta Molina, Iñaki Martín, Nerea Galera, Sergio Mut"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

##Intruducción al trabajo:
Este proyecto trata sobre desarrollar un programa que permita analizar una serie de tickets de compra de supermercado.

El objetivo es enfrentarse a un problema real de tratamiento de datos, realizando un seguimiento de (evolución de precios, compras más habituales, productos más consumidos, supermercado habitual, hora de compra, etc).

Este proyecto ha sido realizado con control de cambios GIT. Tiene un repositorio compartido entre las miembros del grupo llamado ProyectoTD2024 en la plataforma GitHub y en el cual se ven los cambios y desarrollo del trabajo.

##Información del proyecto:
Se dispone de varios tickets para empezar a trabajar y un jupiter notebook de python (TicketPDF2TXT.ipynb) que transforma todos los ficheros con extensión pdf presentes en la carpeta data en ficheros de texto con toda la información.

