---
title: "Untitled"
output: html_document
date: "2024-03-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
```

```{r}
# Instalación automática de paquete.

#Este bloque se encarga de instalar los paquetes necesarios.



packages = c("tidyverse","knitr","reshape2")
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE,repos='http://cran.rediris.es')
  }
  library(x, character.only = TRUE)
})

search()

```

```{r}
#Cargamos en la vble. 'rutas' los archivos que deseamos leeer:
rutas <- list.files("prueba/")
#tiquets <- replicate(rutas, list(NULL))
```

```{r}
#Recorremos los archivos mediante un bucle 'para',
#para así poder cargar en un data frame todos
#los datos de os tiquets:
for (archivo in rutas){
  #Leer línea a línea cada tiquet:
   x <- readLines(paste("prueba",archivo,sep= "/"), encoding = "latin1")
   #Notamos que las primeras líneas de los tiquets son iguales sp:
   prod <- x[8:length(x)]
   producto <- list()
   final <- list()
   enc = FALSE
   for (elemento in prod){
     #Vemos que, el final de cada tiquet es diferente,
     #depende de los productos de cada tiquet.
     #Destacar a partir de la línea donde se encuentra
     #'TOTAL (€)' :
     if (grepl("TOTAL", elemento)){
         enc = TRUE
        }
     if (enc == FALSE){
        producto <- c(producto, elemento)
     }
     if (enc == TRUE){
       final <- c(final, elemento)
     }
   }
   #Creamos el dataframe:
   df <- data.frame(Nombre = x[1], Calle = x[2], Municipio = x[3], Telefono = x[4], Fecha = x[5],  Factura_simpl= x[6] , Productos = producto)
   
  #df <- pivot_longer(df, names_to = "Producto", values_to = "Productos", cols = -c("Nombre","Calle", "Municipio", "Telefono", "Fecha", "Factura_simpl")) 

}

```


